DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.sandbox.paypal.com:443
DEBUG:urllib3.connectionpool:https://api.sandbox.paypal.com:443 "POST /v1/oauth2/token HTTP/1.1" 200 1352
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.sandbox.paypal.com:443
DEBUG:urllib3.connectionpool:https://api.sandbox.paypal.com:443 "POST /v2/checkout/orders HTTP/1.1" 201 501
INFO:root:PayPal callback received with parameters: {'token': '3HF53164U1213950B', 'PayerID': 'T3WE7MUZ25GY2'}
INFO:root:PayPal success callback received for order: 3HF53164U1213950B
INFO:root:Payment order data: {'amount': 15.9, 'created_at': '2025-06-09T10:59:35.927227', 'expires_at': '2025-06-09T11:29:35.927236', 'order_id': '3HF53164U1213950B', 'plan_id': 2, 'promo_code': '', 'telegram_username': 'anupx8898'}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.sandbox.paypal.com:443
DEBUG:urllib3.connectionpool:https://api.sandbox.paypal.com:443 "POST /v1/oauth2/token HTTP/1.1" 200 1352
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.sandbox.paypal.com:443
DEBUG:urllib3.connectionpool:https://api.sandbox.paypal.com:443 "POST /v2/checkout/orders/3HF53164U1213950B/capture HTTP/1.1" 201 1424
ERROR:root:Payment processing error: (psycopg2.errors.UndefinedColumn) column user.telegram_chat_id does not exist
LINE 1: ...ser".telegram_username AS user_telegram_username, "user".tel...
                                                             ^

[SQL: SELECT "user".id AS user_id, "user".telegram_username AS user_telegram_username, "user".telegram_chat_id AS user_telegram_chat_id, "user".pin_hash AS user_pin_hash, "user".created_at AS user_created_at, "user".is_active AS user_is_active, "user".is_banned AS user_is_banned 
FROM "user" 
WHERE "user".telegram_username = %(telegram_username_1)s 
 LIMIT %(param_1)s]
[parameters: {'telegram_username_1': 'anupx8898', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405)